apiVersion: v1
kind: Service
metadata:
  name: articles
  namespace: microservices
  labels:
    app: articles
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: articles
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
      - name: articles
        image: shivastunts/microservices-article-service-testing:v1
        ports:
        - containerPort: 8080