apiVersion: v1
kind: Service
metadata:
  name: authors
  namespace: microservices
  labels:
    app: authors
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: authors
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: authors
    spec:
      containers:
      - name: authors
        image: shivastunts/microservices-authors-service-testing:v1
        ports:
        - containerPort: 8081