apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: microservices
  labels:
    name: eureka
spec:
  selector:
    app: eureka
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-deployment
  namespace: microservices
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  serviceName: eureka-service
  replicas: 5
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: shivastunts/microservices-eureka-testing:v1
          ports:
            - containerPort: 8761





